// <auto-generated />
using System;
using Kodvian.Core.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kodvian.Core.Infrastructure.Migrations
{
    [DbContext(typeof(KodvianDbContext))]
    [Migration("20260922191843_PartnerPeopleLinks")]
    partial class PartnerPeopleLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Address")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int?>("BillingDay")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CommercialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Country")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegalName")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<decimal?>("MonthlyAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Province")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CommercialName");

                    b.HasIndex("Status");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("FullName");

                    b.HasIndex("TaxId");

                    b.ToTable("Developers", (string)null);
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.DeveloperPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("AppliedAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("AppliedCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FinancialMovementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<int>("PeriodMonth")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodYear")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("FinancialMovementId")
                        .IsUnique();

                    b.HasIndex("PaymentDate");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("ContractId", "PeriodYear", "PeriodMonth");

                    b.ToTable("DeveloperPayments", (string)null);
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.DocumentFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("DeveloperPaymentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FinancialMovementId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperPaymentId");

                    b.HasIndex("FinancialMovementId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Sha256");

                    b.HasIndex("UploadedById");

                    b.ToTable("DocumentFiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_DocumentFiles_Owner", "((\"ProjectId\" IS NOT NULL)::int + (\"FinancialMovementId\" IS NOT NULL)::int + (\"DeveloperPaymentId\" IS NOT NULL)::int) = 1");
                        });
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.FinanceSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("HistoryComplete")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("OpeningArs")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("OpeningUsd")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("FinanceSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_FinanceSettings_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.FinancialCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MovementType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("MovementType");

                    b.HasIndex("Name");

                    b.ToTable("FinancialCategories", (string)null);
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.FinancialMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("ExchangeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Funding")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateOnly>("MovementDate")
                        .HasColumnType("date");

                    b.Property<int>("MovementType")
                        .HasColumnType("integer");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateOnly?>("SettlementDate")
                        .HasColumnType("date");

                    b.Property<bool>("SettlementDateEstimated")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DueDate");

                    b.HasIndex("ExchangeId");

                    b.HasIndex("MovementDate");

                    b.HasIndex("MovementType");

                    b.HasIndex("PartnerId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("Status");

                    b.HasIndex("Currency", "SettlementDate");

                    b.HasIndex("MovementDate", "FechaCreacion");

                    b.HasIndex("MovementType", "Status", "DueDate");

                    b.ToTable("FinancialMovements", (string)null);
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Partners", null, t =>
                        {
                            t.HasCheckConstraint("CK_Partners_OnePersonSource", "\"DeveloperId\" IS NULL OR \"UserId\" IS NULL");
                        });
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaCierre")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaEntregaEstimada")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("GoogleDriveFolderUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PorcentajeAvance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("Presupuesto")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ResponsableId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Estado");

                    b.HasIndex("Prioridad");

                    b.HasIndex("ResponsableId");

                    b.HasIndex("ClienteId", "FechaCreacion");

                    b.HasIndex("Estado", "Prioridad", "FechaCreacion");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.ProjectDeveloperAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "DeveloperId")
                        .IsUnique();

                    b.ToTable("ProjectDeveloperAssignments", (string)null);
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.ProjectDeveloperContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("AgreedAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("DeveloperId", "FechaCreacion");

                    b.HasIndex("ProjectId", "DeveloperId", "Activo");

                    b.ToTable("ProjectDeveloperContracts", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProjectDeveloperContracts_FixedAmount", "\"AgreedAmount\" IS NULL OR \"AgreedAmount\" > 0");

                            t.HasCheckConstraint("CK_ProjectDeveloperContracts_Percentage", "\"Percentage\" IS NULL OR (\"Percentage\" >= 0 AND \"Percentage\" <= 100)");
                        });
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.ProjectDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Type");

                    b.HasIndex("ProjectId", "Activo");

                    b.ToTable("ProjectDocuments", (string)null);
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.ProjectDocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("DocumentFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProjectDocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentFileId")
                        .IsUnique();

                    b.HasIndex("ProjectDocumentId");

                    b.HasIndex("UploadedById");

                    b.HasIndex("ProjectDocumentId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ProjectDocumentVersions", (string)null);
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Providers", (string)null);
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("95e52dc4-44f5-4b0b-aabf-4044f28cc55a"),
                            Activo = true,
                            Description = "Acceso total al sistema",
                            FechaCreacion = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("a77176f8-d33a-4c23-b613-f2e73093e1b7"),
                            Activo = true,
                            Description = "Acceso operativo a clientes, proyectos y tareas",
                            FechaCreacion = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Operativo"
                        },
                        new
                        {
                            Id = new Guid("24b2ab35-0c84-4fa8-9c35-eecf5f476bb8"),
                            Activo = true,
                            Description = "Acceso de solo lectura",
                            FechaCreacion = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Solo lectura"
                        },
                        new
                        {
                            Id = new Guid("7bbad1f2-2c26-4dc0-bf74-2213871f7d52"),
                            Activo = true,
                            Description = "Gestion operativa de clientes, equipo, proyectos y tareas",
                            FechaCreacion = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Analista"
                        },
                        new
                        {
                            Id = new Guid("58df40de-1019-4dcf-81dc-55a8a2d06235"),
                            Activo = true,
                            Description = "Acceso limitado a proyectos y tareas asignadas",
                            FechaCreacion = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Desarrollador"
                        });
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.TaskAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UploadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UploadedById");

                    b.HasIndex("TaskId", "UploadId")
                        .IsUnique();

                    b.ToTable("TaskAttachments", (string)null);
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CreadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaFinalizacion")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<decimal?>("HorasEstimadas")
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal?>("HorasReales")
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("OrdenKanban")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Prioridad")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResponsableId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaVencimiento");

                    b.HasIndex("Prioridad");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("ResponsableId");

                    b.HasIndex("ProyectoId", "Estado");

                    b.HasIndex("Estado", "OrdenKanban", "FechaCreacion");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionVersion")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.DeveloperPayment", b =>
                {
                    b.HasOne("Kodvian.Core.Domain.Entities.ProjectDeveloperContract", "Contract")
                        .WithMany("Payments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kodvian.Core.Domain.Entities.FinancialMovement", "FinancialMovement")
                        .WithOne("DeveloperPayment")
                        .HasForeignKey("Kodvian.Core.Domain.Entities.DeveloperPayment", "FinancialMovementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Contract");

                    b.Navigation("FinancialMovement");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.DocumentFile", b =>
                {
                    b.HasOne("Kodvian.Core.Domain.Entities.DeveloperPayment", "DeveloperPayment")
                        .WithMany("Documents")
                        .HasForeignKey("DeveloperPaymentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Kodvian.Core.Domain.Entities.FinancialMovement", "FinancialMovement")
                        .WithMany("Documents")
                        .HasForeignKey("FinancialMovementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Kodvian.Core.Domain.Entities.Project", "Project")
                        .WithMany("Documents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kodvian.Core.Domain.Entities.User", "UploadedBy")
                        .WithMany("UploadedDocuments")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeveloperPayment");

                    b.Navigation("FinancialMovement");

                    b.Navigation("Project");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.FinancialMovement", b =>
                {
                    b.HasOne("Kodvian.Core.Domain.Entities.FinancialCategory", "Category")
                        .WithMany("FinancialMovements")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kodvian.Core.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kodvian.Core.Domain.Entities.User", "CreatedBy")
                        .WithMany("FinancialMovementsCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kodvian.Core.Domain.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kodvian.Core.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kodvian.Core.Domain.Entities.Provider", "Provider")
                        .WithMany("FinancialMovements")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Client");

                    b.Navigation("CreatedBy");

                    b.Navigation("Partner");

                    b.Navigation("Project");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.Partner", b =>
                {
                    b.HasOne("Kodvian.Core.Domain.Entities.Developer", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kodvian.Core.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Developer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.Project", b =>
                {
                    b.HasOne("Kodvian.Core.Domain.Entities.Client", "Cliente")
                        .WithMany("Projects")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kodvian.Core.Domain.Entities.User", "Responsable")
                        .WithMany("Projects")
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.ProjectDeveloperAssignment", b =>
                {
                    b.HasOne("Kodvian.Core.Domain.Entities.Developer", "Developer")
                        .WithMany("ProjectAssignments")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kodvian.Core.Domain.Entities.Project", "Project")
                        .WithMany("DeveloperAssignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.ProjectDeveloperContract", b =>
                {
                    b.HasOne("Kodvian.Core.Domain.Entities.Developer", "Developer")
                        .WithMany("Contracts")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kodvian.Core.Domain.Entities.Project", "Project")
                        .WithMany("DeveloperContracts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.ProjectDocument", b =>
                {
                    b.HasOne("Kodvian.Core.Domain.Entities.User", "CreatedBy")
                        .WithMany("ProjectDocumentsCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kodvian.Core.Domain.Entities.User", "DeletedBy")
                        .WithMany("ProjectDocumentsDeleted")
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kodvian.Core.Domain.Entities.Project", "Project")
                        .WithMany("ProjectDocuments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.ProjectDocumentVersion", b =>
                {
                    b.HasOne("Kodvian.Core.Domain.Entities.DocumentFile", "DocumentFile")
                        .WithMany()
                        .HasForeignKey("DocumentFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kodvian.Core.Domain.Entities.ProjectDocument", "ProjectDocument")
                        .WithMany("Versions")
                        .HasForeignKey("ProjectDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kodvian.Core.Domain.Entities.User", "UploadedBy")
                        .WithMany("ProjectDocumentVersionsUploaded")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentFile");

                    b.Navigation("ProjectDocument");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.TaskAttachment", b =>
                {
                    b.HasOne("Kodvian.Core.Domain.Entities.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kodvian.Core.Domain.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("Kodvian.Core.Domain.Entities.User", "CreadoPor")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kodvian.Core.Domain.Entities.Developer", "Developer")
                        .WithMany("Tasks")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kodvian.Core.Domain.Entities.Project", "Proyecto")
                        .WithMany("Tareas")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kodvian.Core.Domain.Entities.User", "Responsable")
                        .WithMany("Tasks")
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreadoPor");

                    b.Navigation("Developer");

                    b.Navigation("Proyecto");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.User", b =>
                {
                    b.HasOne("Kodvian.Core.Domain.Entities.Developer", "Developer")
                        .WithMany("Users")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Kodvian.Core.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kodvian.Core.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.Client", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.Developer", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("ProjectAssignments");

                    b.Navigation("Tasks");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.DeveloperPayment", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.FinancialCategory", b =>
                {
                    b.Navigation("FinancialMovements");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.FinancialMovement", b =>
                {
                    b.Navigation("DeveloperPayment");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.Project", b =>
                {
                    b.Navigation("DeveloperAssignments");

                    b.Navigation("DeveloperContracts");

                    b.Navigation("Documents");

                    b.Navigation("ProjectDocuments");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.ProjectDeveloperContract", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.ProjectDocument", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.Provider", b =>
                {
                    b.Navigation("FinancialMovements");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Kodvian.Core.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedTasks");

                    b.Navigation("FinancialMovementsCreated");

                    b.Navigation("ProjectDocumentVersionsUploaded");

                    b.Navigation("ProjectDocumentsCreated");

                    b.Navigation("ProjectDocumentsDeleted");

                    b.Navigation("Projects");

                    b.Navigation("Tasks");

                    b.Navigation("UploadedDocuments");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
